### ISSUE TITLE
Adjust length of rewind/fastforward

### ISSUE THREAD

**Issue by ptmkenny** [andreasgrill/alfred-nfremote#2]
Is there any way to adjust the length of the amount of time rewound/fast-forwarded when the button on the remote is pressed?

**Comment by andreasgrill** [comment]
Rewind and fast-forward are simulating a press on the left/right buttons, hence it is only possible to increase the amount of time rewound/fast-forwarded. If you want to achieve this, you could adjust the python script by changing the third parameter of the lines 27 and 28 from "1" to the number of times the button should be pressed.

**Comment by ptmkenny** [comment]
Thanks, that’s just what I needed to know!
